#!/bin/bash
set -e

ROOT=$(dirname $0)/..
INVENTORY=${INVENTORY:-${ROOT}/inventory}

if [ ! -e ${INVENTORY} ]; then
  echo "Please create an inventory file with your hosts."
  echo " cp inventory.example inventory"
  exit 1
fi

if [ -e ${ROOT}/secrets.yml ]; then
  VAULT_ARG=
else
  VAULT_ARG=--ask-vault-pass
fi

exec ansible-playbook ${ROOT}/site.yml -i ${INVENTORY} ${VAULT_ARG} $@
