#!/bin/bash

ROOT=$(dirname $0)/..

if [ ! -e ${ROOT}//inventory ]; then
  echo "Please create an inventory file with your hosts."
  echo " cp inventory.example inventory"
  exit 1
fi

if [ -e ${ROOT}/secrets.yml ]; then
  VAULT_ARG=
else
  VAULT_ARG=--ask-vault-pass
fi

exec ansible-playbook ${ROOT}/site.yml -i ${ROOT}/inventory ${VAULT_ARG} $@
